# Documentation: .gitlab/ci/README.md#manifest-file-to-control-the-buildtest-apps

examples/ethernet/basic:
  enable:
    - if: INCLUDE_DEFAULT == 1
  disable:
    - if: IDF_TARGET in ["esp32c61"]
      temporary: true
      reason: not supported yet # TODO: [esp32c61] IDF-9298
  disable_test:
    - if: IDF_TARGET not in ["esp32"]
      temporary: true
      reason: lack of runners
  depends_components:
    - esp_eth
    - esp_netif
    - lwip
    - esp_event
    - esp_driver_gpio
    - esp_driver_spi

examples/ethernet/enc28j60:
  disable:
    - if: IDF_TARGET in ["esp32c61"]
      temporary: true
      reason: not supported yet # TODO: [esp32c61] IDF-9298
  depends_components:
    - esp_eth
    - esp_netif
    - lwip
    - esp_event
    - esp_driver_gpio
    - esp_driver_spi

examples/ethernet/iperf:
  disable:
    - if: IDF_TARGET in ["esp32c61"]
      temporary: true
      reason: not supported yet # TODO: [esp32c61] IDF-9298
  disable_test:
    - if: IDF_TARGET not in ["esp32"]
      temporary: true
      reason: lack of runners
  depends_components:
    - esp_eth
    - esp_netif
    - lwip
    - esp_event
    - console
    - esp_driver_gpio
    - esp_driver_spi
    - cmd_system
    - ethernet_init
    - protocol_examples_common
